name: rltk
description: A Flutter implementation of the Roguelike toolkit.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  dartemis: ^0.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/t8x8.png
